name: Release Pipeline

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # Step 1: Build all binaries
  build-macos:
    uses: ./.github/workflows/build-macos.yml

  build-linux:
    uses: ./.github/workflows/build-linux.yml

  # Step 2: Publish to package registries
  publish-npm:
    needs: [build-macos, build-linux]
    uses: ./.github/workflows/publish-npm.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gem:
    needs: [build-macos, build-linux]
    uses: ./.github/workflows/publish-gem.yml
    secrets:
      RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

  # Step 3: Update Homebrew
  update-homebrew:
    needs: [build-macos]
    uses: ./.github/workflows/update-homebrew.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  # Step 4: Summary
  release-summary:
    needs: [publish-npm, publish-gem, update-homebrew]
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create release summary
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          echo "## ✅ Release v$VERSION Complete!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📦 Published to:" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ npm: https://www.npmjs.com/package/fastqr" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ RubyGems: https://rubygems.org/gems/fastqr" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Packagist: https://packagist.org/packages/fastqr/fastqr" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Homebrew: brew install tranhuucanh/fastqr/fastqr" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🎯 Installation:" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "# macOS (Homebrew)" >> $GITHUB_STEP_SUMMARY
          echo "brew upgrade fastqr" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Ruby" >> $GITHUB_STEP_SUMMARY
          echo "gem install fastqr" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Node.js" >> $GITHUB_STEP_SUMMARY
          echo "npm install fastqr@$VERSION" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# PHP" >> $GITHUB_STEP_SUMMARY
          echo "composer require fastqr/fastqr" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

