name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Get release info
        id: release
        run: |
          # Get version from release tag (e.g., v1.0.1 → 1.0.1)
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Download and hash source tarball
        id: source
        run: |
          # Download source tarball from GitHub
          curl -L -o source.tar.gz "https://github.com/tranhuucanh/fastqr/archive/refs/tags/v${{ steps.release.outputs.version }}.tar.gz"
          SHA256=$(shasum -a 256 source.tar.gz | cut -d' ' -f1)
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT
          echo "Source SHA256: $SHA256"

      - name: Checkout homebrew-fastqr repo
        uses: actions/checkout@v3
        with:
          repository: tranhuucanh/homebrew-fastqr
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-fastqr

      - name: Update formula
        run: |
          cd homebrew-fastqr
          VERSION="${{ steps.release.outputs.version }}"
          SHA256="${{ steps.source.outputs.sha256 }}"

          echo "Updating formula to version $VERSION with SHA256 $SHA256"

          # Update version
          sed -i "s/version \".*\"/version \"$VERSION\"/" Formula/fastqr.rb

          # Update URL to source tarball
          sed -i "s|url \".*\"|url \"https://github.com/tranhuucanh/fastqr/archive/refs/tags/v$VERSION.tar.gz\"|" Formula/fastqr.rb

          # Update SHA256
          sed -i "s/sha256 \".*\"/sha256 \"$SHA256\"/" Formula/fastqr.rb

          echo "Formula updated:"
          cat Formula/fastqr.rb

      - name: Commit and push
        run: |
          cd homebrew-fastqr
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add Formula/fastqr.rb
          git commit -m "chore: update to v${{ steps.release.outputs.version }}"
          git push
